name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Change directory
        run: cd packages/apps/fortune/recording-oracle

      - name: Install dependencies
        run: yarn install

      - name: Start development server
        run: yarn start:dev
