name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd packages/apps/fortune && yarn

      - name: Start minio
        run: cd packages/apps/fortune/recording-oracle && docker-compose up --d

      - name: Start production application
        run: cd packages/apps/fortune && yarn recording-oracle:prod
